stages:
  preprocess_train:
    cmd: python src/preprocessing/prep_train.py
    deps:
      - src/preprocessing/prep_train.py
      - data/raw/training/p1_extrac.csv
    outs:
      - data/processed/train/
      - data/processed/test/
      - models/pipelines/preprocess.pkl
  train:
    cmd: python src/training/train.py
    deps:
      - src/training/train.py
      - data/processed/train/train_arrays.npz
      - models/pipelines/preprocess.pkl
    outs:
      - models/artifacts/model.pkl
  monitor:
    cmd: python src/monitoring/monitor.py
    deps:
      - src/monitoring/monitor.py
      - models/pipelines/preprocess.pkl
      - data/processed/train/train_arrays.npz
      - data/inference_logs/prediction_log.csv
    outs:
      - data/monitoring_reports/drift_report.html
      - data/monitoring_reports/drift_report.json